### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by tremby**
I've based this atop my other two changesets from today. Let me know if you want me to separate it out.

Among stylistic changes, additions of a lot of descriptions, and some reorganizing, some undocumented commands have been added.

### CODE REVIEW

**Comment by ambientsound** [comment]
Needs rebase after #96 was merged.

**Comment by tremby** [comment]
Rebased.

**Comment by tremby** [comment]
I can switch the order of this and #98 if you prefer.

**Comment by ambientsound** [comment]
Awesome improvement to the documentation, and highly appreciated.

Yes, it would be beneficial to rearrange the order, this can be merged right away as long as the new viewport commands in #98 are moved to that PR.

**Comment by tremby** [comment]
OK, this one is now directly on top of current master.

**Comment by tremby** [comment]
Just changed this a little since it's clear you prefer the `* ` style of lists in markdown rather than the `- ` style.

**Pull request merged**
