### PR TITLE
Updates README

### PR DESCRIPTION
**Pull request by xamebax**
Update README with instructions on setting up workstation for contributors.

### CODE REVIEW

**Comment by tremby** [comment]
I checked out the upstream, then when I wanted to start making contributions, forked the repo and rearranged the remotes in the git repository, so the repo was still at its original location (ambientsound). But this is certainly a more direct route.

I would have made a relative symlink rather than an absolute one:

    ln -s ../[yourgithubhandlegoeshere]/pms $GOPATH/src/github.com/ambientsound/pms

**Comment by ambientsound** [comment]
What do you mean by rearranging the remotes?

**Comment by tremby** [comment]
I mean I started with a clone of your repository, then edited .git/config and renamed it from "origin" to "upstream", then did `git remote add origin git@github.com/tremby/pms.git` and set up branch tracking as appropriate.

All I mean to say is that I didn't come up with this particular issue because of the (convoluted) way I set up my dev environment.

**Comment by ambientsound** [comment]
Please correct me if I'm wrong, but that's not what this patch addresses. See sample output below for what kind of error you'd get by not having aforementioned symlink in place.

```
kimt@nova ~/go/src/github.com $ mv ambientsound/ foobar
kimt@nova ~/go/src/github.com $ cd foobar/pms/
kimt@nova ~/go/src/github.com/foobar/pms $ make install
go install -ldflags="-X main.buildVersion=c605245"
main.go:9:2: cannot find package "github.com/ambientsound/pms/console" in any of:
        /usr/lib/go-1.8/src/github.com/ambientsound/pms/console (from $GOROOT)
        /home/kimt/go/src/github.com/ambientsound/pms/console (from $GOPATH)
main.go:10:2: cannot find package "github.com/ambientsound/pms/pms" in any of:
        /usr/lib/go-1.8/src/github.com/ambientsound/pms/pms (from $GOROOT)
        /home/kimt/go/src/github.com/ambientsound/pms/pms (from $GOPATH)
main.go:11:2: cannot find package "github.com/ambientsound/pms/version" in any of:
        /usr/lib/go-1.8/src/github.com/ambientsound/pms/version (from $GOROOT)
        /home/kimt/go/src/github.com/ambientsound/pms/version (from $GOPATH)
main.go:12:2: cannot find package "github.com/ambientsound/pms/xdg" in any of:
        /usr/lib/go-1.8/src/github.com/ambientsound/pms/xdg (from $GOROOT)
        /home/kimt/go/src/github.com/ambientsound/pms/xdg (from $GOPATH)
Makefile:8: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by tremby** [comment]
I understand that.

I was pointing out how I didn't come across this issue: I had an "ambientsound" directory from the beginning, even though it now points to my own fork of the repository.

Another way to do it would be to make the ambientsound directory and then check out your fork within that.

**Pull request merged**
